name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install checkov flake8 yamllint flask

      - name: Check Terraform code with Checkov
        run: checkov -d terraform/

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.51.1_Linux-64bit.deb

      - name: Build Docker image
        run: docker build -t devsecops-app docker/app/

      - name: Scan Docker image with Trivy
        run: trivy image devsecops-app

      - name: Scan for secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --verbose

      - name: Run simple test
        run: |
          pip install pytest
          pytest tests/
